<a href="https://colab.research.google.com/github/Nishakumari-2004/Churn-Modellling/blob/main/Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
path="/content/drive/MyDrive/Colab Notebooks/Churn_Modelling.csv"
dataset=pd.read_csv(path)
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
dataset.shape

(10000, 14)

In [ ]:
X=dataset.iloc[:,3:13]    #independent features
y=dataset.iloc[:,13]

In [ ]:
# Create dummy variables since these are categorical variables,convert into numerical
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X["Gender"],drop_first=True)

In [ ]:
X=pd.concat([X,geography,gender],axis=1)
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain   Male  
0             1               1        101348.88    False  False  False  
1             0               1        112542.58    False   True  False  
2             1               0        113931.57    False  False  False  
3             0               0         93826.63    False  False  False  
4             1               1         79084.10    False   True  False  
...         ...             ...              ...      ...    ...    ...  
9995          1               0         96270.64    False  False   True  
9996          1               1        101699.77    False  False   True  
9997          0               1         42085.58    False  False  False  
9998          1               0         92888.52     True  False   True  
9999          1               0         38190.78    False  False  False  

[10000 rows x 13 columns]

In [ ]:
 X=X.drop(['Geography','Gender'],axis=1)
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain   Male  
0                  1        101348.88    False  False  False  
1                  1        112542.58    False   True  False  
2                  0        113931.57    False  False  False  
3                  0         93826.63    False  False  False  
4                  1         79084.10    False   True  False  
...              ...              ...      ...    ...    ...  
9995               0         96270.64    False  False   True  
9996               1        101699.77    False  False   True  
9997               1         42085.58    False  False  False  
9998               0         92888.52     True  False   True  
9999               0         38190.78    False  False  False  

[10000 rows x 11 columns]

In [ ]:
#Splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train


array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [ ]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [ ]:
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense,InputLayer,Activation,Embedding,Flatten,BatchNormalization
from scikeras.wrappers import KerasClassifier
from keras.activations import relu,sigmoid
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout


In [ ]:
#Initialising the ANN
classifier=Sequential()

In [ ]:
# Add the input layer
classifier.add(InputLayer(shape=(11,)))

In [ ]:
# adding the first hidden layer
classifier.add(Dense(units=10,kernel_initializer='he_uniform',activation='relu'))
# relu works well in hidden layers ,it prevents vanishing gradient problem
#can use he normal also apart from he uniform ,that also works well with relu

In [ ]:
#adding the second hidden layer
classifier.add(Dense(units=20,kernel_initializer='he_uniform',activation='relu'))

In [ ]:
#adding the third hidden layer
classifier.add(Dense(units=15 ,kernel_initializer='he_uniform',activation='relu'))

In [ ]:
#adding the output layer
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [ ]:
#Compiling  the ANN ,this is binary classification
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
#Fitting ANN to the training set
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.5729 - loss: 0.7544 - val_accuracy: 0.8046 - val_loss: 0.4555
Epoch 2/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7994 - loss: 0.4359 - val_accuracy: 0.8198 - val_loss: 0.4198
Epoch 3/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8263 - loss: 0.3983 - val_accuracy: 0.8266 - val_loss: 0.3975
Epoch 4/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8393 - loss: 0.3677 - val_accuracy: 0.8296 - val_loss: 0.3867
Epoch 5/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8479 - loss: 0.3560 - val_accuracy: 0.8307 - val_loss: 0.3846
Epoch 6/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8507 - loss: 0.3568 - val_accuracy: 0.8398 - val_loss: 0.3769
Epoch 7/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.8518 - loss: 0.3543 - val_accuracy: 0.8383 - val_loss: 0.3780
Epoch 8/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8566 - loss: 0.3406 - val_acc

In [ ]:
#Predicting the Test set results
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step


In [ ]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1487,  108],
       [ 187,  218]])

In [ ]:
#accuracy score
from sklearn.metrics import accuracy_score
score= accuracy_score(y_pred,y_test)
score

0.8525